
DROP INDEX IF EXISTS  XJIDJ001EPF;
DROP INDEX IF EXISTS  XJIDJ002EPF;
DROP INDEX IF EXISTS  XJXFI001EPF;
DROP INDEX IF EXISTS  XEPFGR01EPF;
DROP INDEX IF EXISTS  XEPFGR02EPF;
DROP INDEX IF EXISTS  XPRXI001EPF;

DROP TABLE IF EXISTS JID_JOBID;
DROP TABLE IF EXISTS JXF_XREF;
DROP TABLE IF EXISTS EPF_GRP_EET_PROFL;
DROP TABLE IF EXISTS PRX_INEX;

CREATE TABLE JID_JOBID (
	JID_JOB_ID        CHAR(20) NOT NULL,
	CMS_SRC_SYS_CD    CHAR(5) NOT NULL,
	JID_EFCTV_DT      TIMESTAMP NOT NULL,
	JID_TRMNTN_DT     TIMESTAMP,
	JID_JOBID_STAT_CD CHAR(5) NOT NULL,
	JID_OWNER_ID      CHAR(20) NOT NULL,
	MODIFY_USUS_ID    CHAR(20) NOT NULL,
	MODIFY_DT_TM      TIMESTAMP NOT NULL,
	JID_DESC_TXT      VARCHAR(1024) NOT NULL,
	CONSTRAINT JID_JOBID_PKEPF PRIMARY KEY (JID_JOB_ID,CMS_SRC_SYS_CD,JID_EFCTV_DT)
);

CREATE UNIQUE INDEX XJIDJ001EPF ON JID_JOBID (JID_JOB_ID,CMS_SRC_SYS_CD,JID_EFCTV_DT);
CREATE INDEX XJIDJ002EPF ON JID_JOBID (JID_JOB_ID,CMS_SRC_SYS_CD);

CREATE TABLE JXF_XREF (
	GRP_GRP_ID      CHAR(10) NOT NULL,
	SGP_SBGRP_ID    CHAR(10) NOT NULL,
	CMS_SRC_SYS_CD  CHAR(5) NOT NULL,
	JXF_EFCTV_DT    TIMESTAMP NOT NULL,
	JXF_TRMNTN_DT   TIMESTAMP,
	JID_JOB_ID      CHAR(20) NOT NULL,
	JID_EFCTV_DT    TIMESTAMP NOT NULL,
	MODIFY_USUS_ID  CHAR(20) NOT NULL,
	MODIFY_DT_TM    TIMESTAMP NOT NULL,
	CONSTRAINT JXF_XREF_PKEPF PRIMARY KEY (GRP_GRP_ID,SGP_SBGRP_ID,CMS_SRC_SYS_CD,JXF_EFCTV_DT)
);

CREATE UNIQUE INDEX XJXFI001EPF ON JXF_XREF (GRP_GRP_ID,SGP_SBGRP_ID,CMS_SRC_SYS_CD,JXF_EFCTV_DT);


CREATE TABLE EPF_GRP_EET_PROFL (
	JID_JOB_ID CHAR(20) NOT NULL,
	GRP_GRP_ID CHAR(10) NOT NULL,
	CMS_SRC_SYS_CD CHAR(5) NOT NULL,
	EPF_EFCTV_DT TIMESTAMP NOT NULL,
	SGP_SBGRP_ID CHAR(10) NOT NULL,
	JID_CMS_SRC_SYS_CD CHAR(5),
	JID_EFCTV_DT TIMESTAMP,
	CMS_EET_PFL_STS_CD CHAR(5) NOT NULL,
	EPF_ACTVTY_GDY_QTY INTEGER NOT NULL,
	EPF_ADRS_CHNG_IND SMALLINT NOT NULL,
	EPF_ADR_CHG_WB_IND SMALLINT NOT NULL,
	CMS_PCP_CHNG_CD CHAR(5) NOT NULL,
	CMS_PDO_CHNG_CD CHAR(5) NOT NULL,
	CMS_NTWK_CHG_CD CHAR(5) NOT NULL,
	EPF_SSCRBR_TRM_IND SMALLINT NOT NULL,
	EPF_RPTFU_CLMC_IND SMALLINT NOT NULL,
	EPF_RPTFU_CLMR_IND SMALLINT NOT NULL,
	EPF_RPTFU_DEPT_IND SMALLINT NOT NULL,
	EPF_RPTFU_EMPL_IND SMALLINT NOT NULL,
	EPF_DEP_TRM_IND SMALLINT NOT NULL,
	EPF_RPTFR_CLMC_IND SMALLINT NOT NULL,
	EPF_RPTFR_CLMR_IND SMALLINT NOT NULL,
	EPF_RPTFR_DEPT_IND SMALLINT NOT NULL,
	EPF_RPTFR_EMPL_IND SMALLINT NOT NULL,
	EPF_PIC_PMG_IND SMALLINT NOT NULL,
	EPF_PIC_PCP_IND SMALLINT NOT NULL,
	EPF_PIC_PDO_IND SMALLINT NOT NULL,
	EPF_PIC_NTWK_IND SMALLINT NOT NULL,
	EPF_DFLT_PMG_ID CHAR(20) NOT NULL,
	EPF_DFLT_PCP_ID CHAR(20) NOT NULL,
	EPF_DFLT_PDO_ID CHAR(20) NOT NULL,
	EPF_DFLT_NTWK_ID CHAR(20) NOT NULL,
	CMS_EFF_DT_CHG_CD CHAR(5),
	CMS_TRM_DT_CHG_CD CHAR(5),
	CMS_MDF_EFF_DT_CD CHAR(5) NOT NULL,
	CMS_MDF_TRM_DT_CD CHAR(5) NOT NULL,
	EPF_DEP_CVG_IND SMALLINT NOT NULL,
	CMS_GEN_COB_CD CHAR(5) NOT NULL,
	EPF_GEN_PREX_IND SMALLINT NOT NULL,
	EPF_DEP_USE_IND SMALLINT NOT NULL,
	EPF_RTR_TRM_MO_QTY INTEGER,
	EPF_RTR_TRM_MO_IND SMALLINT NOT NULL,
	EPF_RETRO_DAY_QTY INTEGER,
	EPF_RETRO_DAY_IND SMALLINT NOT NULL,
	CMS_MDL_IN_USE_CD CHAR(5),
	EPF_RTRV_CLINT_IND SMALLINT NOT NULL,
	EPF_CRT_USR_ID CHAR(20),
	EPF_CRT_DT_TM TIMESTAMP,
	EPF_OAD_PRCS_IND SMALLINT NOT NULL,
	CMS_GRP_TYP_PUL_CD CHAR(5) NOT NULL,
	EPF_PRVW_IND SMALLINT NOT NULL,
	EPF_TRMNTN_DT TIMESTAMP,
	CMS_PRFL_LVL_CD CHAR(5),
	CMS_AT_TRM_PRCS_CD CHAR(5),
	EPF_GEN_MDCR_IND SMALLINT NOT NULL,
	CMS_DOB_SRC_CD CHAR(5),
	EPF_VDTSPC_PRV_IND SMALLINT NOT NULL,
	MODIFY_USUS_ID CHAR(20) NOT NULL,
	MODIFY_DT_TM TIMESTAMP NOT NULL,
	EPF_PCP_RETRO_QTY INTEGER,
	EPF_PDO_RETRO_QTY INTEGER,
	EPF_NTWK_RETRO_QTY INTEGER,
	EPF_DURNL_CAP_IND SMALLINT,
	CMS_GRPSGP_INEX_CD CHAR(5) NOT NULL,
	CMS_PROD_INEX_CD CHAR(5) NOT NULL,
	CMS_PREX_ENDDT_CAL CHAR(5) NOT NULL,
	EPF_ADDR_FLIP_IND SMALLINT NOT NULL,
	CMS_ACTN_INEX_CD CHAR(5),
	CMS_PROCES_MEDD_CD CHAR(5),
	EPF_PROC_MDRSK_IND SMALLINT,
	CMS_ADRS_REPL CHAR(5) DEFAULT 'Y' NOT NULL,
	CMS_XREF_DB_CHK CHAR(5) DEFAULT 'Y' NOT NULL,
	CMS_PRE_EX_CHG CHAR(5) DEFAULT 'N' NOT NULL,
	CMS_HYPHEN_NAMES CHAR(5) DEFAULT 'N' NOT NULL,
	CMS_GENU_ADD_SWCH CHAR(5) DEFAULT 'U' NOT NULL,
	CMS_GENU_UPD_SWCH CHAR(5) DEFAULT 'N' NOT NULL,
	CMS_ADD_CXLD_MBR CHAR(5) DEFAULT 'N' NOT NULL,
	CMS_AUPD_PAR CHAR(5) DEFAULT 'N' NOT NULL,
	CMS_AUPD_FRST_MTH_TERM CHAR(5) DEFAULT 'N' NOT NULL,
	CMS_OVR45_SSN_EXMP_SW CHAR(5) DEFAULT 'N' NOT NULL,
	CMS_CNTY_FROM_ZIP_IND CHAR(5) DEFAULT 'N' NOT NULL,
	CMS_SSB_CD CHAR(5) DEFAULT 'N' NOT NULL,
	CMS_PCP_PROV_EPDS2_IND CHAR(5) DEFAULT 'N' NOT NULL,
	CMS_SSCRBR_TRM_IND CHAR(5) DEFAULT 'Y' NOT NULL,
	CMS_DEP_TRM_IND CHAR(5) DEFAULT 'Y' NOT NULL,
	EPF_AUPD_REC_CNT DECIMAL(4,1) DEFAULT 0 NOT NULL,
	EPF_AUPD_ADDS DECIMAL(4,1) DEFAULT 0 NOT NULL,
	EPF_AUPD_CHANGES DECIMAL(4,1) DEFAULT 0 NOT NULL,
	EPF_AUPD_EXP_TERM DECIMAL(4,1) DEFAULT 0 NOT NULL,
	EPF_AUPD_IMP_TERM DECIMAL(4,1) DEFAULT 0 NOT NULL,
	EPF_AUPD_DFT_PVDR DECIMAL(4,1) DEFAULT 0 NOT NULL,
	EPF_AUPD_ERRORS_CNT DECIMAL(4,1) DEFAULT 0 NOT NULL,
	CMS_TOLERANCE_CHK_SW CHAR(5) DEFAULT 'N' NOT NULL,
	EPF_OVRD_HDR_DT TIMESTAMP,
	CMS_GRP_TYPE_IND CHAR(5) DEFAULT 'R' NOT NULL,
	CMS_DT_OF_HIRE_IND CHAR(5) DEFAULT 'N' NOT NULL,
	EPF_MBR_FRST_NM_CHK_IND CHAR(1),
	EPF_PROV_CHNG_DT TIMESTAMP,
	EPF_NTWK_CHNG_DT TIMESTAMP,
	EPF_PREV_ENRLMNT_CNT DECIMAL(13,0) DEFAULT 0 NOT NULL,
	EPF_BKUP_PREV_ENRLMNT_CNT DECIMAL(13,0) DEFAULT 0 NOT NULL,
	EPF_ERR_TLRNC_LVL_PCT DECIMAL(3,2) DEFAULT 0 NOT NULL,
	EPF_HDR_EFCTV_DT TIMESTAMP,
	EPF_EXCHNG_NBR SMALLINT DEFAULT 0 NOT NULL,
	EPF_EXCHNG_ENTRPR_CD CHAR(2),
	EPF_EXCHNG_NM VARCHAR(20),
	EPF_COB_OVRD_IND CHAR(1),
	EPF_PCP_ERR_SUPP_IND CHAR(1) DEFAULT 'N' NOT NULL,
	EPF_DUP_COV_ERR_SUPP_IND CHAR(1) DEFAULT 'N' NOT NULL,
	EPF_BEN_EFCTV_DT_IND CHAR(1) DEFAULT 'A' NOT NULL,
	CONSTRAINT EPF_GRP_EET_PROFL_PKEPF PRIMARY KEY (JID_JOB_ID,GRP_GRP_ID,CMS_SRC_SYS_CD,EPF_EFCTV_DT)
);

CREATE UNIQUE INDEX XEPFGR01EPF ON EPF_GRP_EET_PROFL (JID_JOB_ID,GRP_GRP_ID,CMS_SRC_SYS_CD,EPF_EFCTV_DT);
CREATE INDEX XEPFGR02EPF ON EPF_GRP_EET_PROFL (JID_JOB_ID,GRP_GRP_ID,CMS_SRC_SYS_CD,SGP_SBGRP_ID,CMS_EET_PFL_STS_CD);


CREATE TABLE PRX_INEX (
	JID_JOB_ID CHAR(20) NOT NULL,
	GRP_GRP_ID CHAR(10) NOT NULL,
	SGP_SBGRP_ID CHAR(10) NOT NULL,
	CMS_SRC_SYS_CD CHAR(5) NOT NULL,
	PRX_EFCTV_DT TIMESTAMP NOT NULL,
	PRX_TRMNTN_DT TIMESTAMP,
	CMS_PROD_TYPE_CD CHAR(5) NOT NULL,
	EPF_EFCTV_DT TIMESTAMP NOT NULL,
	MODIFY_USUS_ID CHAR(20) NOT NULL,
	MODIFY_DT_TM TIMESTAMP NOT NULL,
	CONSTRAINT PRX_INEX_PKEPF PRIMARY KEY (JID_JOB_ID,GRP_GRP_ID,SGP_SBGRP_ID,CMS_SRC_SYS_CD,CMS_PROD_TYPE_CD,PRX_EFCTV_DT)
);
CREATE UNIQUE INDEX XPRXI001EPF ON PRX_INEX (JID_JOB_ID,GRP_GRP_ID,SGP_SBGRP_ID,CMS_SRC_SYS_CD,CMS_PROD_TYPE_CD,PRX_EFCTV_DT);

