
DROP INDEX IF EXISTS  XGCTGR01GCT;
DROP INDEX IF EXISTS  XGCTGR02GCT;

DROP TABLE IF EXISTS GCT_GRP_CNTCT

CREATE TABLE GCT_GRP_CNTCT (
	JID_JOB_ID CHAR(20) NOT NULL,
	GRP_GRP_ID CHAR(10) NOT NULL,
	SGP_SBGRP_ID CHAR(10) NOT NULL,
	CMS_SRC_SYS_CD CHAR(5) NOT NULL,
	GCT_CNTC_EFCTV_DT TIMESTAMP NOT NULL,
	GCT_SQNC_NBR SMALLINT NOT NULL,
	CMS_CNTCT_TYP_CD CHAR(5) NOT NULL,
	EPF_EFCTV_DT TIMESTAMP NOT NULL,
	CMS_TTL_CD CHAR(5),
	GCT_FRST_NM_TXT CHAR(25),
	GCT_MDL_NM_TXT CHAR(20),
	GCT_LAST_NM_TXT CHAR(35),
	CMS_NM_SFX_CD CHAR(5),
	GCT_ADRS_1_TXT CHAR(25),
	GCT_ADRS_2_TXT CHAR(25),
	GCT_CTY_TXT CHAR(18),
	GCT_ST_ABRV_CD CHAR(2),
	GCT_GRP_POSTL_CD CHAR(15),
	GCT_GRP_ZIP_4_CD CHAR(4),
	GCT_GRP_CNTY_CD CHAR(5),
	CMS_CNTRY_CD CHAR(5),
	GCT_PRMRY_EMAL_TXT CHAR(75),
	GCT_ALT_EMAL_TXT CHAR(75),
	GCT_CTC_FRNEX_NBR CHAR(10),
	GCT_CNTCT_AREA_CD CHAR(3),
	GCT_CNTCT_PHN_NBR CHAR(7),
	GCT_CNTCT_PHN_EXT CHAR(5),
	GCT_FAX_FRNEX_NBR CHAR(10),
	GCT_FAX_AREA_CD CHAR(3),
	GCT_FAX_PHN_NBR CHAR(7),
	GCT_FAX_PHN_EXT CHAR(5),
	GCT_ASSOC_ID CHAR(20),
	GCT_PRMY_CNTCT_IND SMALLINT,
	CMS_MAIL_PRFRNC_CD CHAR(5) NOT NULL,
	GCT_TRMNTN_DT TIMESTAMP,
	CMS_PRMRY_LANG_CD CHAR(5),
	CMS_SCNDRY_LANG_CD CHAR(5),
	MODIFY_USUS_ID CHAR(20) NOT NULL,
	MODIFY_DT_TM TIMESTAMP NOT NULL,
	CONSTRAINT GCT_GRP_CNTCT_PK PRIMARY KEY (JID_JOB_ID,GRP_GRP_ID,SGP_SBGRP_ID,CMS_SRC_SYS_CD,GCT_CNTC_EFCTV_DT,GCT_SQNC_NBR,CMS_CNTCT_TYP_CD),
	CONSTRAINT "GRP$GCT" FOREIGN KEY (GRP_GRP_ID,CMS_SRC_SYS_CD) REFERENCES GRP(GRP_GRP_ID,CMS_SRC_SYS_CD) ON DELETE RESTRICT
);
CREATE UNIQUE INDEX XGCTGR01GCT ON GCT_GRP_CNTCT (JID_JOB_ID,GRP_GRP_ID,SGP_SBGRP_ID,CMS_SRC_SYS_CD,GCT_CNTC_EFCTV_DT,GCT_SQNC_NBR,CMS_CNTCT_TYP_CD);
CREATE INDEX XGCTGR02GCT ON GCT_GRP_CNTCT (JID_JOB_ID,GRP_GRP_ID,SGP_SBGRP_ID,CMS_SRC_SYS_CD);

