
DROP TABLE IF EXISTS  JID_JOBID_VW;

CREATE TABLE JID_JOBID_VW (
	JID_JOB_ID CHAR(20),
	CMS_SRC_SYS_CD CHAR(5),
	JID_EFCTV_DT TIMESTAMP,
	JID_TRMNTN_DT TIMESTAMP,
	JID_JOBID_STAT_CD CHAR(5),
	JID_OWNER_ID CHAR(20),
	MODIFY_USUS_ID CHAR(20),
	MODIFY_DT_TM TIMESTAMP,
	JID_DESC_TXT VARCHAR(1024),
	CONSTRAINT JID_JOBID_PK04 PRIMARY KEY (JID_JOB_ID,CMS_SRC_SYS_CD,JID_EFCTV_DT)
);
