
INSERT INTO JID_JOBID_VW (JID_JOB_ID, CMS_SRC_SYS_CD, JID_EFCTV_DT, JID_TRMNTN_DT, JID_JOBID_STAT_CD, JID_OWNER_ID, MODIFY_USUS_ID, MODIFY_DT_TM,JID_DESC_TXT)
    VALUES ('aa', 'WGS20', PARSEDATETIME('2006-03-01 13:19:45', 'yyyy-MM-dd HH:mm:ss'), null, 'A    ', 'EETUSER1', 'EETUSER1', CURRENT_TIMESTAMP(), 'Test data');
