INSERT INTO TYP_CD_VW (CDCI_CD_ITM_ID, CDCI_ITM_VER_NBR, CDCV_DOMN_VAL, CDCV_CD_VAL_NM, CDCV_DESC_TXT, UCFR_FLTR_VAL, CDIR_NTRNL_CD_NM)
VALUES (1286, 0, 'D950', 'SRC=D950', 'The source of this transaction is the Diamond 950', 'EET', 'Transaction Source System');
INSERT INTO TYP_CD_VW (CDCI_CD_ITM_ID, CDCI_ITM_VER_NBR, CDCV_DOMN_VAL, CDCV_CD_VAL_NM, CDCV_DESC_TXT, UCFR_FLTR_VAL, CDIR_NTRNL_CD_NM)
VALUES (1286, 0, 'FCETS', 'SRC=FCETS', 'The source of this transaction is the Facets System', 'EET', 'Transaction Source System');
INSERT INTO TYP_CD_VW (CDCI_CD_ITM_ID, CDCI_ITM_VER_NBR, CDCV_DOMN_VAL, CDCV_CD_VAL_NM, CDCV_DESC_TXT, UCFR_FLTR_VAL, CDIR_NTRNL_CD_NM)
VALUES (1286, 0, 'M204', 'SRC=M204', 'The transaction source system code is M204', 'EET', 'Transaction Source System');
INSERT INTO TYP_CD_VW (CDCI_CD_ITM_ID, CDCI_ITM_VER_NBR, CDCV_DOMN_VAL, CDCV_CD_VAL_NM, CDCV_DESC_TXT, UCFR_FLTR_VAL, CDIR_NTRNL_CD_NM)
VALUES (1286, 0, 'QCARE', 'SRC=QCare', 'The source of this transaction is the QCare System', 'EET', 'Transaction Source System');
INSERT INTO TYP_CD_VW (CDCI_CD_ITM_ID, CDCI_ITM_VER_NBR, CDCV_DOMN_VAL, CDCV_CD_VAL_NM, CDCV_DESC_TXT, UCFR_FLTR_VAL, CDIR_NTRNL_CD_NM)
VALUES (1286, 0, 'STAR', 'SRC=STAR', 'The source of this transaction is the STAR System', 'EET', 'Transaction Source System');
INSERT INTO TYP_CD_VW (CDCI_CD_ITM_ID, CDCI_ITM_VER_NBR, CDCV_DOMN_VAL, CDCV_CD_VAL_NM, CDCV_DESC_TXT, UCFR_FLTR_VAL, CDIR_NTRNL_CD_NM)
VALUES (1286, 0, 'WGS13', 'SRC=WGS13', 'The source of this transaction is the WGS 1.3 Syst', 'EET', 'Transaction Source System');
INSERT INTO TYP_CD_VW (CDCI_CD_ITM_ID, CDCI_ITM_VER_NBR, CDCV_DOMN_VAL, CDCV_CD_VAL_NM, CDCV_DESC_TXT, UCFR_FLTR_VAL, CDIR_NTRNL_CD_NM)
VALUES (1286, 0, 'WGS20', 'SRC=WGS20', 'The source of this transaction is the WGS 2.0 Syst', 'EET', 'Transaction Source System');
INSERT INTO TYP_CD_VW (CDCI_CD_ITM_ID, CDCI_ITM_VER_NBR, CDCV_DOMN_VAL, CDCV_CD_VAL_NM, CDCV_DESC_TXT, UCFR_FLTR_VAL, CDIR_NTRNL_CD_NM)
VALUES (1286, 0, 'D950', 'SRC=D950', 'The source of this transaction is the Diamond 950', 'SPCM', 'Transaction Source System');
INSERT INTO TYP_CD_VW (CDCI_CD_ITM_ID, CDCI_ITM_VER_NBR, CDCV_DOMN_VAL, CDCV_CD_VAL_NM, CDCV_DESC_TXT, UCFR_FLTR_VAL, CDIR_NTRNL_CD_NM)
VALUES (1286, 0, 'FCETS', 'SRC=FCETS', 'The source of this transaction is the Facets System', 'SPCM', 'Transaction Source System');
INSERT INTO TYP_CD_VW (CDCI_CD_ITM_ID, CDCI_ITM_VER_NBR, CDCV_DOMN_VAL, CDCV_CD_VAL_NM, CDCV_DESC_TXT, UCFR_FLTR_VAL, CDIR_NTRNL_CD_NM)
VALUES (1286, 0, 'M204', 'SRC=M204', 'The transaction source system code is M204', 'SPCM', 'Transaction Source System');
