DROP TABLE IF EXISTS TYP_CD_VW;

CREATE TABLE TYP_CD_VW (
  CDCI_CD_ITM_ID      NUMBER(10),
  CDCI_ITM_VER_NBR    NUMBER(5),
  CDCV_DOMN_VAL       VARCHAR(10),
  CDCV_CD_VAL_NM      VARCHAR(30),
  CDCV_DESC_TXT       VARCHAR(240),
  UCFR_FLTR_VAL       VARCHAR(10),
  CDIR_NTRNL_CD_NM    VARCHAR(30),
  CONSTRAINT PK_TYP_CD_VW01 PRIMARY KEY(CDCI_CD_ITM_ID,CDCV_CD_VAL_NM, UCFR_FLTR_VAL)
);
